import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/Header";
import { MantineProvider } from "@mantine/core";

import "@/app/globals.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden text-sm">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-slate-100 antialiased h-full grid grid-rows-[min-content_minmax(0,1fr)]`}
      >
        <MantineProvider>
          <Header />
          <main className="overflow-auto">

            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
